server {
    listen 80;
    server_name localhost;

    # Главный эндпоинт: перекидываем запросы в контейнер с Django
    location / {
        proxy_pass http://web:8000;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    # Папка со статикой (админка Django и Swagger)
    location /static/ {
        alias /app/static/;
    }
}
